/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creationvoilier.gui;

import creationvoilier.dao.BateauDAO;
import creationvoilier.dao.ClasseDAO;
import creationvoilier.dao.ClubDAO;
import creationvoilier.dao.PersonneDAO;
import creationvoilier.dao.ProprietaireDAO;
import creationvoilier.dao.SerieDAO;
import creationvoilier.model.Bateau;
import creationvoilier.model.Classe;
import creationvoilier.model.Club;
import creationvoilier.model.Personne;
import creationvoilier.model.Proprietaire;
import creationvoilier.model.Serie;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class CreationVoilier extends javax.swing.JFrame {

    /**
     * Creates new form CreationVoilier
     */
    public CreationVoilier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personneJDialog = new javax.swing.JDialog();
        titreJLabel = new javax.swing.JLabel();
        prenomJLabel = new javax.swing.JLabel();
        nomJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        addresse1JLabel = new javax.swing.JLabel();
        addresse2JLabel = new javax.swing.JLabel();
        villeJLabel = new javax.swing.JLabel();
        paysJLabel = new javax.swing.JLabel();
        langueJLabel = new javax.swing.JLabel();
        telephoneJLabel = new javax.swing.JLabel();
        dialogValidJButton = new javax.swing.JButton();
        dialogAnnulJButton = new javax.swing.JButton();
        prenomJTextField = new javax.swing.JTextField();
        nomPersoJTextField = new javax.swing.JTextField();
        emailJTextField = new javax.swing.JTextField();
        addresse1JTextField = new javax.swing.JTextField();
        cpJTextField = new javax.swing.JTextField();
        villeJTextfield = new javax.swing.JTextField();
        paysJTextField = new javax.swing.JTextField();
        langueJTextfield = new javax.swing.JTextField();
        telephoneJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        clubComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        creationJLabel = new javax.swing.JLabel();
        nomVoilierJLabel = new javax.swing.JLabel();
        serieJLabel = new javax.swing.JLabel();
        classeJLabel = new javax.swing.JLabel();
        proprietaireJLabel = new javax.swing.JLabel();
        serieComboBox = new javax.swing.JComboBox<>();
        classeJComboBox = new javax.swing.JComboBox<>();
        proprietaireJComboBox = new javax.swing.JComboBox<>();
        nomJTextField = new javax.swing.JTextField();
        creerProprietaireJButton = new javax.swing.JButton();
        validerJButton = new javax.swing.JButton();
        annulerJButton = new javax.swing.JButton();
        serieJButton = new javax.swing.JButton();

        personneJDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                personneJDialogWindowClosed(evt);
            }
        });

        titreJLabel.setText("Nouveau Proprietaire");

        prenomJLabel.setText("Prenom:");

        nomJLabel.setText("Nom:");

        emailJLabel.setText("Email:");

        addresse1JLabel.setText("Addresse1:");

        addresse2JLabel.setText("Code Postal:");

        villeJLabel.setText("Ville:");

        paysJLabel.setText("Pays:");

        langueJLabel.setText("Langue:");

        telephoneJLabel.setText("Téléphone:");

        dialogValidJButton.setText("Valider");
        dialogValidJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogValidJButtonActionPerformed(evt);
            }
        });

        dialogAnnulJButton.setText("Annuler");
        dialogAnnulJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogAnnulJButtonActionPerformed(evt);
            }
        });

        telephoneJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneJTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Club Nautique:");

        clubComboBox.setModel(new javax.swing.DefaultComboBoxModel(ClubDAO.findAll().toArray()));

        javax.swing.GroupLayout personneJDialogLayout = new javax.swing.GroupLayout(personneJDialog.getContentPane());
        personneJDialog.getContentPane().setLayout(personneJDialogLayout);
        personneJDialogLayout.setHorizontalGroup(
            personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personneJDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomJLabel)
                    .addComponent(prenomJLabel)
                    .addComponent(emailJLabel)
                    .addComponent(addresse1JLabel)
                    .addComponent(addresse2JLabel)
                    .addComponent(villeJLabel)
                    .addComponent(paysJLabel)
                    .addComponent(langueJLabel)
                    .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(telephoneJLabel)))
                .addGap(57, 57, 57)
                .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titreJLabel)
                    .addComponent(prenomJTextField)
                    .addComponent(nomPersoJTextField)
                    .addComponent(emailJTextField)
                    .addComponent(addresse1JTextField)
                    .addComponent(cpJTextField)
                    .addComponent(villeJTextfield)
                    .addComponent(paysJTextField)
                    .addComponent(langueJTextfield)
                    .addComponent(telephoneJTextField)
                    .addComponent(clubComboBox, 0, 172, Short.MAX_VALUE))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personneJDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dialogAnnulJButton)
                .addGap(18, 18, 18)
                .addComponent(dialogValidJButton)
                .addGap(22, 22, 22))
        );
        personneJDialogLayout.setVerticalGroup(
            personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personneJDialogLayout.createSequentialGroup()
                .addComponent(titreJLabel)
                .addGap(18, 18, 18)
                .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomJLabel)
                    .addComponent(prenomJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomJLabel)
                    .addComponent(nomPersoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailJLabel)
                    .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addresse1JLabel)
                    .addComponent(addresse1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addresse2JLabel)
                    .addComponent(cpJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(villeJLabel)
                    .addComponent(villeJTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paysJLabel)
                    .addComponent(paysJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(langueJLabel)
                    .addComponent(langueJTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneJLabel)
                    .addComponent(telephoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clubComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(personneJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialogAnnulJButton)
                    .addComponent(dialogValidJButton))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        creationJLabel.setText("ENREGISTREMENT D'UN VOILIER");

        nomVoilierJLabel.setText("Nom du voilier:");

        serieJLabel.setText("Serie du voilier:");

        classeJLabel.setText("Classe du voilier:");
        classeJLabel.setVisible(false);

        proprietaireJLabel.setText("Proprietaire:");

        serieComboBox.setModel(new javax.swing.DefaultComboBoxModel(SerieDAO.findAll().toArray()));

        classeJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>());
        classeJComboBox.setVisible(false);

        proprietaireJComboBox.setModel(new javax.swing.DefaultComboBoxModel(ProprietaireDAO.findAll().toArray()));
        proprietaireJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proprietaireJComboBoxActionPerformed(evt);
            }
        });

        creerProprietaireJButton.setText("+");
        creerProprietaireJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerProprietaireJButtonActionPerformed(evt);
            }
        });

        validerJButton.setText("Valider");
        validerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerJButtonActionPerformed(evt);
            }
        });

        annulerJButton.setText("Annuler");

        serieJButton.setText("Valider la serie");
        serieJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serieJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(serieJLabel)
                            .addComponent(nomVoilierJLabel)
                            .addComponent(classeJLabel)
                            .addComponent(proprietaireJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(proprietaireJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(creerProprietaireJButton))
                            .addComponent(nomJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(serieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(serieJButton)))
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(creationJLabel)
                            .addComponent(annulerJButton))
                        .addGap(18, 18, 18)
                        .addComponent(validerJButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creationJLabel)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomVoilierJLabel)
                    .addComponent(nomJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serieJLabel)
                    .addComponent(serieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serieJButton))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classeJLabel)
                    .addComponent(classeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proprietaireJLabel)
                    .addComponent(proprietaireJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creerProprietaireJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validerJButton)
                    .addComponent(annulerJButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dialogValidJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogValidJButtonActionPerformed

            String prenom = nomPersoJTextField.getText();
            String nom = nomPersoJTextField.getText();
            String email = emailJTextField.getText();
            String addresse1= addresse1JTextField.getText();
            String cp=cpJTextField.getText();
            String ville = villeJTextfield.getText();
            String pays = paysJTextField.getText();
            String langue = langueJTextfield.getText();
            String tel = telephoneJTextField.getText();
            Club club = (Club) clubComboBox.getSelectedItem();
            if(prenom.isEmpty() || nom.isEmpty() || email.isEmpty() || addresse1.isEmpty()|| cp.isEmpty()||ville.isEmpty()||pays.isEmpty() || langue.isEmpty()||tel.isEmpty() ){
                JOptionPane jop;
                jop=new JOptionPane();
                jop.showMessageDialog(null,
                        "INFORMATION MANQUANTE!!!!!",
                        " warning",JOptionPane.WARNING_MESSAGE);
            }else{
                try {
                    Personne personne = new Personne(0,  prenom, nom,  email, null, addresse1,cp, ville, pays,  langue,  tel);
                    
                    int personneId=PersonneDAO.create(personne);
                    
                    personne.setId(personneId);
                    Proprietaire proprietaire = new Proprietaire(0,club,personne.getPersonneId(), personne.getPrenom(), personne.getNom(), personne.getEmail(), "", personne.getAddresse1(), personne.getAddresse2(), personne.getVille(), personne.getPays(), personne.getLangue(), personne.getTel());
                    ProprietaireDAO.create(proprietaire);
                    
                    JOptionPane jop1;
                    jop1=new JOptionPane();
                    jop1.showMessageDialog(null,
                            "le proprietaire a été créé",
                            " Success",JOptionPane.INFORMATION_MESSAGE);
                    
                    personneJDialog.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(CreationVoilier.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }//GEN-LAST:event_dialogValidJButtonActionPerformed

    private void dialogAnnulJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogAnnulJButtonActionPerformed
      personneJDialog.dispose();
    }//GEN-LAST:event_dialogAnnulJButtonActionPerformed

    private void creerProprietaireJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerProprietaireJButtonActionPerformed
        personneJDialog.pack();
        personneJDialog.setVisible(true);
    }//GEN-LAST:event_creerProprietaireJButtonActionPerformed

    private void serieJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieJButtonActionPerformed
      Serie serie = (Serie) serieComboBox.getSelectedItem();
       int id = serie.getSerie_id();
       ArrayList<Classe> classes =ClasseDAO.findallFromSerieId(id);
    DefaultComboBoxModel model = new DefaultComboBoxModel(classes.toArray());
    classeJComboBox.setModel(model);
        classeJLabel.setVisible(true);
        classeJComboBox.setVisible(true);
    }//GEN-LAST:event_serieJButtonActionPerformed

    private void proprietaireJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proprietaireJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proprietaireJComboBoxActionPerformed

    private void validerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerJButtonActionPerformed
      String nomVoilier = nomJTextField.getText();
      if(nomVoilier.equals("")){
          JOptionPane jop;
          jop=new JOptionPane();
          nomJTextField.setBorder(BorderFactory.createLineBorder(Color.RED, 2, rootPaneCheckingEnabled));
          jop.showMessageDialog(null,
    "nom du voilier vide!!!!",
    " warning",JOptionPane.WARNING_MESSAGE);
          return;
      }
      Classe classe =(Classe) classeJComboBox.getSelectedItem();
      Proprietaire proprietaire =(Proprietaire) proprietaireJComboBox.getSelectedItem();
      Bateau bateau = new Bateau(-1,nomVoilier,0,proprietaire,classe);
        try {
            BateauDAO.create(bateau);
        } catch (SQLException ex) {
            Logger.getLogger(CreationVoilier.class.getName()).log(Level.SEVERE, null, ex);
        }
           JOptionPane jop1;
           jop1=new JOptionPane();
           jop1.showMessageDialog(null,
    "le voilier à été créé.",
    " success",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_validerJButtonActionPerformed

    private void telephoneJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneJTextFieldActionPerformed

    private void personneJDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_personneJDialogWindowClosed
         ArrayList<Proprietaire> proprietaires =ProprietaireDAO.findAll();
    DefaultComboBoxModel model = new DefaultComboBoxModel(proprietaires.toArray());
    proprietaireJComboBox.setModel(model);
    }//GEN-LAST:event_personneJDialogWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreationVoilier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreationVoilier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreationVoilier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreationVoilier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreationVoilier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresse1JLabel;
    private javax.swing.JTextField addresse1JTextField;
    private javax.swing.JLabel addresse2JLabel;
    private javax.swing.JButton annulerJButton;
    private javax.swing.JComboBox<String> classeJComboBox;
    private javax.swing.JLabel classeJLabel;
    private javax.swing.JComboBox<String> clubComboBox;
    private javax.swing.JTextField cpJTextField;
    private javax.swing.JLabel creationJLabel;
    private javax.swing.JButton creerProprietaireJButton;
    private javax.swing.JButton dialogAnnulJButton;
    private javax.swing.JButton dialogValidJButton;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel langueJLabel;
    private javax.swing.JTextField langueJTextfield;
    private javax.swing.JLabel nomJLabel;
    private javax.swing.JTextField nomJTextField;
    private javax.swing.JTextField nomPersoJTextField;
    private javax.swing.JLabel nomVoilierJLabel;
    private javax.swing.JLabel paysJLabel;
    private javax.swing.JTextField paysJTextField;
    private javax.swing.JDialog personneJDialog;
    private javax.swing.JLabel prenomJLabel;
    private javax.swing.JTextField prenomJTextField;
    private javax.swing.JComboBox<String> proprietaireJComboBox;
    private javax.swing.JLabel proprietaireJLabel;
    private javax.swing.JComboBox<String> serieComboBox;
    private javax.swing.JButton serieJButton;
    private javax.swing.JLabel serieJLabel;
    private javax.swing.JLabel telephoneJLabel;
    private javax.swing.JTextField telephoneJTextField;
    private javax.swing.JLabel titreJLabel;
    private javax.swing.JButton validerJButton;
    private javax.swing.JLabel villeJLabel;
    private javax.swing.JTextField villeJTextfield;
    // End of variables declaration//GEN-END:variables
}
